// Slide: Agenda
// This script renders the agenda/menu for the presentation

window.currentSlideRender = function(container) {
    container.innerHTML = '';

    const content = `
        <div class="w-full h-full flex flex-col items-center justify-center bg-gray-900 text-white relative overflow-hidden">
            
            <!-- Background Elements -->
            <div class="absolute inset-0 bg-[url('slide_cover/assets/dark_bg.jpg')] bg-cover bg-center opacity-20"></div>
            <div class="absolute inset-0 bg-gradient-to-br from-gray-900 via-gray-900/90 to-black"></div>

            <!-- Title -->
            <div class="z-10 mb-16 text-center animate-fade-in-down">
                <h2 class="text-4xl md:text-5xl font-bold tracking-wider text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
                    演示流程
                </h2>
                <div class="h-1 w-24 bg-blue-500 mx-auto mt-4 rounded-full"></div>
            </div>

            <!-- Menu Grid -->
            <div id="agenda-grid" class="z-10 grid grid-cols-1 md:grid-cols-4 gap-6 w-full max-w-7xl px-8">
                <!-- Generated by JS based on agendaItems -->
            </div>
        </div>
    `;

    container.innerHTML = content;

    // Render Grid Items
    const grid = container.querySelector('#agenda-grid');
    if (typeof agendaItems !== 'undefined') {
        agendaItems.forEach((item, index) => {
            const card = document.createElement('div');
            card.className = `group relative bg-gray-800/50 backdrop-blur-sm border border-gray-700 rounded-xl p-6 cursor-pointer hover:bg-gray-700/50 transition-all duration-500 hover:-translate-y-2 hover:shadow-2xl hover:shadow-${item.color}-500/20 opacity-0 translate-y-10`;
            card.style.animation = `fade-in-up 0.5s ease-out forwards ${0.2 + index * 0.1}s`;
            
            card.onclick = () => {
                // Exit Animation
                const allCards = grid.children;
                Array.from(allCards).forEach(c => {
                    // Remove animation to allow transition to take over
                    c.style.animation = 'none';
                    // Ensure the element is visible for transition (in case animation left it weirdly)
                    c.style.opacity = getComputedStyle(c).opacity;
                    c.style.transform = getComputedStyle(c).transform;

                    // Apply new styles for exit
                    requestAnimationFrame(() => {
                        if (c === card) {
                            c.style.transform = 'scale(10)';
                            c.style.opacity = '0';
                        } else {
                            c.style.transform = 'translateY(100vh)';
                            c.style.opacity = '0';
                        }
                    });
                });
                
                // Wait for animation then jump
                setTimeout(() => {
                    const idx = slides.findIndex(s => s.id === item.id);
                    if(idx >= 0) loadSlide(idx);
                }, 500);
            };

            card.innerHTML = `
                <div class="absolute inset-0 bg-gradient-to-br from-${item.color}-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity rounded-xl"></div>
                <div class="flex flex-col items-center text-center space-y-4">
                    <div class="w-16 h-16 rounded-full bg-${item.color}-900/30 flex items-center justify-center group-hover:scale-110 transition-transform duration-300">
                        <i class="fa-solid ${item.icon} text-${item.color}-400 text-2xl"></i>
                    </div>
                    <h3 class="text-xl font-bold text-gray-100 group-hover:text-${item.color}-300 transition-colors">${item.title}</h3>
                    <p class="text-sm text-gray-400 group-hover:text-gray-300">${item.sub}</p>
                </div>
            `;
            grid.appendChild(card);
        });
    }

    // Add keyframes for entrance
    if (!document.getElementById('anim-style-agenda')) {
        const style = document.createElement('style');
        style.id = 'anim-style-agenda';
        style.textContent = `
            @keyframes fade-in-up {
                to { opacity: 1; transform: translateY(0); }
            }
        `;
        document.head.appendChild(style);
    }

    // Animations (Title)
    if (window.animate) {
        window.animate(
            '.animate-fade-in-down',
            { y: [-50, 0], opacity: [0, 1] },
            { duration: 0.8 }
        );
    }
};
